[package]
name = "bevy_github_ci_template"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.8"
rand = {version = "0.8", features = ["small_rng"]}
bevy_jornet = "0.1.3"
glam = { version = "0.21"}